[wokwi]
version = 1
firmware = "build/8_single_digit_seg.elf"
elf = "build/8_single_digit_seg.elf"
board = "esp32-devkit-c-v4"
baudrate = 115200

[simulation]
enableSerialMonitor = true
logLevel = "info"